<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2 class="text-center text-dark mt-5">Admin Login</h2>
            <div class="card my-5">

                <form class="card-body cardbody-color p-lg-5" action="admin/login" method="post">

                    <div class="text-center">
                        <img src="<?=$this->getAssetUrl("Admin::images/icon-logo.png")?>" class="img-fluid profile-image-pic img-thumbnail rounded-circle my-3"
                             width="200px" alt="profile">
                    </div>

                    <div class="mb-3">
                        <input name="username" type="text" class="form-control" id="Username" aria-describedby="emailHelp"
                               placeholder="User Name">
                    </div>
                    <div class="mb-3">
                        <input name="password" type="password" class="form-control" id="password" placeholder="password">
                    </div>
                    <div class="text-center"><button type="submit" class="btn btn-primary px-5 mb-5 w-100">Login</button></div>
                </form>
            </div>

        </div>
    </div>
</div>