<!-- Navbar -->
<nav class="navbar navbar-dark bg-dark navbar-expand-sm">
    <!-- Toggle button -->
    <div class="container-xxl bd-gutter">
        <a class="navbar-brand" href="<?= $this->getBaseUrl() ?>">
            <img src="assets/images/icon-logo.png" height="30px" style="filter: invert(1)"/>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar"
                aria-controls="offcanvasDarkNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar"
             aria-labelledby="offcanvasDarkNavbarLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Menu</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
                    <block id="body.header.links.left"/>
                </ul>
                <ul class="navbar-nav">
                    <block id="body.header.links.right"/>
                </ul>
            </div>
        </div>
    </div>
</nav>
<!-- Navbar -->