<div class="profile-pic">
    <div class="count-indicator">
        <i class="fa fa-user-o"></i>
    </div>
    <div class="profile-name">
        <h5 class="mb-0 font-weight-normal">Henry Klein</h5>
    </div>
</div>
<a href="#" id="profile-dropdown" data-bs-toggle="dropdown"><i class="mdi mdi-dots-vertical"></i></a>
<div class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list" aria-labelledby="profile-dropdown">
    <block id="sidebar.user.options"/>
</div>