<a href="<?=$this->url->get('/admin/logout')?>" class="dropdown-item preview-item">
    <div class="preview-thumbnail">
        <div class="preview-icon bg-dark rounded-circle">
            <i class="fa fa-sign-out text-primary"></i>
        </div>
    </div>
    <div class="preview-item-content">
        <p class="preview-subject ellipsis mb-1 text-small">Logout</p>
    </div>
</a>
<div class="dropdown-divider"></div>